name: "package"

on:
  schedule:
    - cron: "0 12 * * 3"
  pull_request:
  push:
    branches:
      - main
      - develop
      - "release/**"
    paths:
      - "**.dart"
      - "./*.yaml"
      - .github/workflows/package.yaml
  release:
    types: [published]

# call the base workflow with the package path
jobs:
  logic_blocks:
    uses: kerberjg/dart_flutter_ci_experiments/.github/workflows/pipeline.yaml@8ad47932f2fb94ccc84ae69f1057bf446454fb0e
    with:
      path: .
      min-publish-score: 120
